const randomStrings = ["Adriano", "Luana", "Matioli", "Naiara"];

const numericObject = {
    a: 1,
    b: 2,
    c: 3
}

const students = [
    {name: 'Ana', age: 20},
    {name: 'João', age: 21},
    {name: 'Maria', age: 19},
    {name: 'Pedro', age: 22},
    {name: 'Fernanda', age: 18},
    {name: 'Carlos', age: 25},
    {name: 'Lucas', age: 21},
    {name: 'Beatriz', age: 24},
    {name: 'Roberto', age: 30},
    {name: 'Marta', age: 27},
    {name: 'Diego', age: 22},
    {name: 'Camila', age: 19},
    {name: 'Renata', age: 28},
    {name: 'Henrique', age: 21},
    {name: 'Victor', age: 23},
    {name: 'Sofia', age: 20},
    {name: 'Raquel', age: 29},
    {name: 'Rafael', age: 26},
    {name: 'Daniela', age: 18},
    {name: 'Luis', age: 31},
    {name: 'Isabella', age: 20},
    {name: 'Amanda', age: 19},
    {name: 'Leonardo', age: 24},
    {name: 'Gabriela', age: 22},
    {name: 'Marcelo', age: 27},
    {name: 'Ricardo', age: 25},
    {name: 'Felipe', age: 19},
    {name: 'Letícia', age: 28},
    {name: 'Natália', age: 26},
    {name: 'Bruno', age: 23},
    {name: 'Thiago', age: 21},
    {name: 'André', age: 30},
    {name: 'Juliana', age: 18},
    {name: 'Gustavo', age: 19},
    {name: 'Fábio', age: 21},
    {name: 'Eduardo', age: 29},
    {name: 'Cláudia', age: 26},
    {name: 'Bianca', age: 19},
    {name: 'Cristiane', age: 28},
    {name: 'Márcio', age: 31},
    {name: 'Júlia', age: 20},
    {name: 'Caio', age: 21},
    {name: 'Carolina', age: 19},
    {name: 'Patrícia', age: 23},
    {name: 'Alex', age: 25},
    {name: 'Vanessa', age: 24},
    {name: 'Mônica', age: 27},
    {name: 'Luana', age: 22},
    {name: 'Vitor', age: 19},
    {name: 'Isadora', age: 28}
  ];

export { randomStrings, numericObject, students }
